config/routes.rb
Rails.application.routes.draw do
  resources :file_resources, except: [:edit, :show, :update] do
    member do
      get :download_file, as: :download
      get :pet_report
      get :product_report_xlsx
    end
  end
  root to: "file_resources#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_resource.rb
class FileResource < ApplicationRecord
  include UploadFile
  before_destroy -> { delete_file(name) }
  has_one :pet, dependent: :destroy
  has_many :products, dependent: :destroy, inverse_of: :file_resource
  validates_presence_of :name
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :file_resource
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :file_resource, inverse_of: :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_resources_controller.rb
class FileResourcesController < ApplicationController
  before_action :set_file_resource, only: [:destroy, :download_file, :pet_report, :product_report_xlsx]
  include UploadFile

  # GET /file_resources
  # GET /file_resources.json
  def index
    @file_resources = FileResource.all
  end

  # GET /file_resources/new
  def new
    @file_resource = FileResource.new
  end


  # POST /file_resources
  # POST /file_resources.json
  def create
    #recibo nombre original del archivo
    name = params[:file_resource][:name].original_filename

    #remuevo extension 
    name_file = name.gsub(/\.zip+$/,'')

    #asgino mediante random + fecha_actual el nuevo nombre del archivo
    final_name = "#{Date.today.strftime("%d%m%Y")}_#{name_file}_#{Random.rand(100..999)}.zip" 
    
    #valido que el content_type sea zip
    c_type = params[:file_resource][:name].content_type
   
    if c_type != "application/zip"
      flash[:notice] = "extension #{c_type} no valid, only .zip"
      redirect_to new_file_resource_path
      else
        #creo el objeto archivo
        @file_resource = FileResource.new(name: final_name)
        
        #subo el archivo mediante el modulo UploadFile
        upload_content(params[:file_resource][:name], final_name)

        path_file = Rails.root.join('app','files',final_name)
        f_file_se = final_name.gsub(/\.zip+$/,'')

        #hago la extraccion del archivo
        extract_zip(path_file,Rails.root.join('app','files', f_file_se))
        
        #recorro archivo de texto
        txt_file = Rails.root.join('app','files',"#{f_file_se}/pet.txt")
        pet_data = read_txt_file(txt_file) if File.exist?(txt_file)
        
        #construyo pet
        @pet = @file_resource.build_pet(name: pet_data[0], age: pet_data[1], color: pet_data[2])

        product_file = Rails.root.join('app','files',"#{f_file_se}/product.txt")
        product_data = read_product_file(product_file) if File.exist?(product_file)
        @product = @file_resource.products.build(product_data)
        
        respond_to do |format|
          if @file_resource.save
            #guardo archivo de texto
            @pet.save
            @product.each {|p| p.save}
            format.html { redirect_to file_resources_path, notice: 'File resource was successfully created.' }
            format.json { render :show, status: :created, location: @file_resource }
          else
            format.html { render :new }
            format.json { render json: @file_resource.errors, status: :unprocessable_entity }
          end
        end
      end
    end

  def download_file
    fname_path = Rails.root.join('app','files', @file_resource.name)
    send_file fname_path, filename: @file_resource.name, type: 'zip', disposition: 'attachment'
  end

  def pet_report
    pdf = render_to_string pdf: "pet_report.pdf",
          show_as_html: false,
          template: "file_resources/file_resource_pdf",
          encoding: "UTF-8"
          
    send_data pdf, filename: "pet_report_#{@file_resource.id}.pdf", type: "application/pdf", disposition: "attachment"
  end

  def product_report_xlsx
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"product_#{@file_resource.id}.xlsx\""}
    end
  end

  # DELETE /file_resources/1
  # DELETE /file_resources/1.json
  def destroy
    @file_resource.destroy
    respond_to do |format|
      format.html { redirect_to file_resources_url, notice: 'File resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_resource
      @file_resource = FileResource.find(params[:id])
      rescue => exception
        flash[:notice] = "#{params[:id]} File not found"
        redirect_to file_resources_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_resource_params
      params.require(:file_resource).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alerts
		alert = (flash[:alert] || flash[:error] || flash[:notice])
    if alert
      js add_gritter(alert, sticky: false, time: 3000)
    end
	end
end

app/helpers/file_resources_helper.rb
module FileResourcesHelper
end

app/views/file_resources/_form.html.erb
<div class="card mt-5 col-md-6" style="margin: 0 auto;">
<div class="card-body">
<%= form_with(model: file_resource, local: true, multipart: true) do |form| %>
  <% if file_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_resource.errors.count, "error") %> prohibited this file_resource from being saved:</h2>

      <ul>
      <% file_resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.file_field :name, required: true, class: 'form-control' %>
  </div>

  <div class="actions" style="text-align: center">
    <%= form.submit class: 'mt-2 btn btn-sm btn-success' %>
  </div>
<% end %>
</div>
</div>

app/views/file_resources/edit.html.erb
<h1>Editing File Resource</h1>

<%= render 'form', file_resource: @file_resource %>

<%= link_to 'Show', @file_resource %> |
<%= link_to 'Back', file_resources_path %>

app/views/file_resources/file_resource_pdf.pdf.erb
<!doctype html>
<html>
<head>
  <meta charset='utf-8' />
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
</head>
<body>
<div id="content">
  <h3 style="border: 1px solid #ccc;
      color: black;
      text-align: center; border-radius: 4px">Pet PDF</h3>
  <br>
  <br>
    <div class="card">
      <div class="card-header">
      <b> Fecha Creación: </b><%= @file_resource.created_at.strftime("%d/%m/%Y")%>
      </div>
      <div class="card-header text-capitalize">
        <b>Nombre Archivo :</b> <%= @file_resource.name %>
      </div>
      <div class="card-header text-capitalize">
        <b>Nombre Pet :</b> <%= @file_resource.pet.name %>
      </div>
      <div class="card-header text-capitalize">
        <b>Edad Pet :</b> <%= @file_resource.pet.age %> Años
      </div>
      <div class="card-header text-capitalize">
        <b>Color Pet :</b> <%= @file_resource.pet.color %>
      </div>
    </div>
</div>
<div>
</div>
</body>
</html>

app/views/file_resources/index.html.erb
<br><br>
<h2>File Resources</h2>
<div class="mt-3 card" style="border-margin: 0 auto;
    display: block;
    border-radius: 4px;">
  <div class="card-body">
    <div class="table-responsive">
    <table class="table table-hover" id="datatable_files">
  <thead style="background-color: dodgerblue;
    color: white">
    <tr style="text-align: center">
      <th>Name</th>
      <th>Zip File</th>
      <th>Pdf File</th>
      <th>Xlsx File</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @file_resources.each do |file_resource| %>
      <tr style="text-align:center">
        <td><%= file_resource.name %></td>
        <td><%= link_to 'Download Zip', download_file_resource_path(file_resource.id), target: "_self",class: 'btn btn-sm btn-success', style: 'color: white' %></td>
      <td><%= link_to 'Download Pdf', pet_report_file_resource_path(file_resource.id,format: :pdf), class: 'btn btn-sm btn-primary', style: 'color: white', target: "blank" %></td>

      <td><%= link_to 'Download as .xlsx', product_report_xlsx_file_resource_path(file_resource.id,format: :xlsx), class: 'btn btn-sm btn-info', style: 'color: white', target: "blank" %></td>
        <td><%= link_to 'Destroy', file_resource, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger', style: 'color: white' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>

<%= link_to 'New File Resource', new_file_resource_path, class: 'btn btn-sm btn-success', style: 'color: white' %>

app/views/file_resources/new.html.erb
<h1 style="text-align:center" class="mt-5"">New File Resource</h1>

<%= render 'form', file_resource: @file_resource %>

<%= link_to 'Back', file_resources_path, style:'color: white; display: table; margin: 0 auto;',class: 'mt-3 btn btn-sm btn-primary' %>

app/views/file_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @file_resource.name %>
</p>

<%= link_to 'Edit', edit_file_resource_path(@file_resource) %> |
<%= link_to 'Back', file_resources_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  </head>

  <body>
  <%= render "partials/nav" %>
  <br>
  <br>
    <div class="container col-md-10">
      <%= alerts %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_nav.html.erb
<header class="navbar navbar-expand-lg fixed-top navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/">File Upload</a>
</header>